"
" .vimrc
"

" General {{{1
set encoding=utf-8                  " encoding used inside vim
set hidden                          " buffer becomes hidden when it is abandoned
set autoread                        " automatically reload files changed outside of vim
set backspace=indent,eol,start      " allow backspacing over everything in insert mode
set updatetime=1000                 " time in millisecond that is waited to fire CursorHold autocommand event
set timeout                         " time out on mappings and key codes
set timeoutlen=1000                 " time in millisecond that is waited for a mapped key sequence to complete
set ttimeoutlen=100                 " time in millisecond that is waited for a key code to complete
set lazyredraw                      " don't update the display when executing macros
let mapleader="\\"                  " define leader key for custom mappings

" Spaces and tabs {{{1
set tabstop=4                       " number of visual spaces per <Tab>
set shiftwidth=4                    " number of spaces to use for each step of (auto)indent
set shiftround                      " round indent to multiple of 'shiftwidth'
set expandtab                       " tabs are spaces
set autoindent                      " always set autoindenting on
set list                            " display unprintable characters
set listchars=tab:»\ ,trail:·       " customize the unprintable characters

" Colors {{{1
syntax enable                       " enable syntax processing
set termguicolors                   " enable true colors support
set background=dark                 " adjust the color groups
colorscheme hybrid                  " load color scheme

" User Interface {{{1
set title                           " show the filename in window titlebar
set number                          " show line numbers
set numberwidth=4                   " minimal number of columns to use for the line number
set signcolumn=yes                  " always draw the sign column
set cursorline                      " highlight the screen line of the cursor
set virtualedit=block               " allow virtual editing in visual mode
set scrolloff=5                     " minimal number of screen lines to above and below the cursor
set sidescrolloff=5                 " minimal number of screen columns to keep to the left and to the right of the cursor
set textwidth=120                   " maximum width of text that is being inserted
set colorcolumn=+1                  " highlight the screen column of the 'textwidth' value
set nowrap                          " don't wrap lines

" Status line {{{1
set laststatus=2                    " always show the status line
set statusline=                     " determines the content of the status line
set statusline+=\ %n\ \|            " - buffer number
set statusline+=\ %f                " - filename
set statusline+=\ %m%r%w            " - modified flag, readonly flag, preview flag
set statusline+=%=                  " - right align
set statusline+=%y                  " - filetype
set statusline+=\ %3l:%-3c          " - line + column
set statusline+=\ %3p%%\            " - percentage through file

" Command line {{{1
set showcmd                         " show command in bottom bar
set wildmenu                        " improve command-line completion
set wildignorecase                  " ignore case for file completion
set wildignore+=.DS_Store           " ignore some patterns for file completion:
set wildignore+=*.jpg,*.jpeg,*.png,*.gif    " - ignore image files
set wildignore+=*.eot,*.ttf,*.woff,*.woff2  " - ignore font files
set wildignore+=*/node_modules/*,*/vendor/* " - ignore vendor directories
set wildignore+=*/dist/*                    " - ignore build directories

" Search {{{1
set ignorecase                      " ignore case when searching
set smartcase                       " override the 'ignorecase' option if the search pattern contains upper case characters
set hlsearch                        " highlight search results
set incsearch                       " makes search act like search in modern browsers

" Autocomplete {{{1
set completeopt=menu                " show popup menu to show possible completions

" Backup {{{1
set nobackup                        " no backup before overwriting file
set nowritebackup                   " no backup before overwriting file
set noswapfile                      " don't use a swapfile

" Filetype {{{1
filetype plugin on                  " enable loading plugin files for specific file types
filetype indent on                  " enable loading indent files for specific file types

" Mapping {{{1
" Quickfix mapping {{{2
nnoremap <silent> [q :<C-U>exe v:count1"cprevious"<CR>zv
nnoremap <silent> ]q :<C-U>exe v:count1"cnext"<CR>zv
nnoremap <silent> [Q :exe "cfirst"<CR>zv
nnoremap <silent> ]Q :exe "clast"<CR>zv

" Location mapping {{{2
nnoremap <silent> [l :<C-U>exe v:count1"lprevious"<CR>zv
nnoremap <silent> ]l :<C-U>exe v:count1"lnext"<CR>zv
nnoremap <silent> [L :exe "lfirst"<CR>zv
nnoremap <silent> ]L :exe "llast"<CR>zv

" Buffer mapping {{{2
nnoremap <silent> [b :<C-U>exe v:count1"bprevious"<CR>
nnoremap <silent> ]b :<C-U>exe v:count1"bnext"<CR>
nnoremap <silent> [B :exe "bfirst"<CR>
nnoremap <silent> ]B :exe "blast"<CR>

" Autocmd {{{1
augroup templates
    autocmd!
    autocmd BufNewFile *.php silent! 0r $HOME/.vim/templates/php.tpl
    autocmd BufNewFile *.vue silent! 0r $HOME/.vim/templates/vue.tpl
augroup END

augroup toggle_relativenumber
    autocmd!
    " show relative numbers in a buffer that has focus and is in normal mode
    autocmd BufEnter,FocusGained,InsertLeave,WinEnter * if &number | :set relativenumber | endif
    autocmd BufLeave,FocusLost,InsertEnter,WinLeave * if &number | :set norelativenumber | endif
augroup END
